// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for ParseDateRequestKind.
const (
	ParseDateRequestKindDefer ParseDateRequestKind = "defer"
	ParseDateRequestKindDue   ParseDateRequestKind = "due"
)

// Valid indicates whether the value is a known member of the ParseDateRequestKind enum.
func (e ParseDateRequestKind) Valid() bool {
	switch e {
	case ParseDateRequestKindDefer:
		return true
	case ParseDateRequestKindDue:
		return true
	default:
		return false
	}
}

// Defines values for ParseDateResponseSource.
const (
	Ai    ParseDateResponseSource = "ai"
	Rules ParseDateResponseSource = "rules"
)

// Valid indicates whether the value is a known member of the ParseDateResponseSource enum.
func (e ParseDateResponseSource) Valid() bool {
	switch e {
	case Ai:
		return true
	case Rules:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusActive    ProjectStatus = "active"
	ProjectStatusCompleted ProjectStatus = "completed"
	ProjectStatusDropped   ProjectStatus = "dropped"
	ProjectStatusOnHold    ProjectStatus = "on_hold"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusActive:
		return true
	case ProjectStatusCompleted:
		return true
	case ProjectStatusDropped:
		return true
	case ProjectStatusOnHold:
		return true
	default:
		return false
	}
}

// Defines values for RepeatRuleFrom.
const (
	RepeatRuleFromCompletion RepeatRuleFrom = "completion"
	RepeatRuleFromDue        RepeatRuleFrom = "due"
)

// Valid indicates whether the value is a known member of the RepeatRuleFrom enum.
func (e RepeatRuleFrom) Valid() bool {
	switch e {
	case RepeatRuleFromCompletion:
		return true
	case RepeatRuleFromDue:
		return true
	default:
		return false
	}
}

// Defines values for RepeatUnit.
const (
	Day   RepeatUnit = "day"
	Month RepeatUnit = "month"
	Week  RepeatUnit = "week"
	Year  RepeatUnit = "year"
)

// Valid indicates whether the value is a known member of the RepeatUnit enum.
func (e RepeatUnit) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	case Week:
		return true
	case Year:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusActive    TaskStatus = "active"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusDropped   TaskStatus = "dropped"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusActive:
		return true
	case TaskStatusCompleted:
		return true
	case TaskStatusDropped:
		return true
	default:
		return false
	}
}

// Defines values for ListProjectsParamsStatus.
const (
	ListProjectsParamsStatusActive    ListProjectsParamsStatus = "active"
	ListProjectsParamsStatusAll       ListProjectsParamsStatus = "all"
	ListProjectsParamsStatusCompleted ListProjectsParamsStatus = "completed"
	ListProjectsParamsStatusDropped   ListProjectsParamsStatus = "dropped"
	ListProjectsParamsStatusOnHold    ListProjectsParamsStatus = "on_hold"
)

// Valid indicates whether the value is a known member of the ListProjectsParamsStatus enum.
func (e ListProjectsParamsStatus) Valid() bool {
	switch e {
	case ListProjectsParamsStatusActive:
		return true
	case ListProjectsParamsStatusAll:
		return true
	case ListProjectsParamsStatusCompleted:
		return true
	case ListProjectsParamsStatusDropped:
		return true
	case ListProjectsParamsStatusOnHold:
		return true
	default:
		return false
	}
}

// Defines values for ListTasksParamsView.
const (
	ListTasksParamsViewAll       ListTasksParamsView = "all"
	ListTasksParamsViewAvailable ListTasksParamsView = "available"
	ListTasksParamsViewCompleted ListTasksParamsView = "completed"
	ListTasksParamsViewDue       ListTasksParamsView = "due"
	ListTasksParamsViewFlagged   ListTasksParamsView = "flagged"
	ListTasksParamsViewInbox     ListTasksParamsView = "inbox"
)

// Valid indicates whether the value is a known member of the ListTasksParamsView enum.
func (e ListTasksParamsView) Valid() bool {
	switch e {
	case ListTasksParamsViewAll:
		return true
	case ListTasksParamsViewAvailable:
		return true
	case ListTasksParamsViewCompleted:
		return true
	case ListTasksParamsViewDue:
		return true
	case ListTasksParamsViewFlagged:
		return true
	case ListTasksParamsViewInbox:
		return true
	default:
		return false
	}
}

// ApiToken A personal API token used to authenticate MCP clients. The secret is only returned once, at creation.
type ApiToken struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`

	// TokenPrefix First characters of the token, for display
	TokenPrefix string `json:"token_prefix"`
}

// CompleteTaskResponse defines model for CompleteTaskResponse.
type CompleteTaskResponse struct {
	// NextTask The next occurrence created for a repeating task
	NextTask *Task `json:"next_task,omitempty"`
	Task     Task  `json:"task"`
}

// Counts Badge counts for the sidebar
type Counts struct {
	// DueSoon Available tasks due within the next 24 hours
	DueSoon   int `json:"due_soon"`
	Flagged   int `json:"flagged"`
	Inbox     int `json:"inbox"`
	Overdue   int `json:"overdue"`
	ReviewDue int `json:"review_due"`
}

// CreateApiTokenRequest defines model for CreateApiTokenRequest.
type CreateApiTokenRequest struct {
	Name string `json:"name"`
}

// CreateApiTokenResponse defines model for CreateApiTokenResponse.
type CreateApiTokenResponse struct {
	// ApiToken A personal API token used to authenticate MCP clients. The secret is only returned once, at creation.
	ApiToken ApiToken `json:"api_token"`

	// Token The full secret token. Shown once; store it in your MCP client config.
	Token string `json:"token"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string  `json:"name"`
	Note *string `json:"note,omitempty"`

	// ParentId Parent project (three levels max; the parent must be at depth 0 or 1)
	ParentId           *openapi_types.UUID `json:"parent_id,omitempty"`
	ReviewIntervalDays *int                `json:"review_interval_days,omitempty"`
	Sequential         *bool               `json:"sequential,omitempty"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Color *string `json:"color,omitempty"`
	Name  string  `json:"name"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	DeferUntil *time.Time `json:"defer_until,omitempty"`
	DueAt      *time.Time `json:"due_at,omitempty"`
	Flagged    *bool      `json:"flagged,omitempty"`
	Note       *string    `json:"note,omitempty"`

	// ProjectId Omit to put the task in the inbox
	ProjectId *openapi_types.UUID `json:"project_id,omitempty"`

	// RepeatRule How a task repeats. "from" controls whether the next occurrence is scheduled relative to the completion date or the previous due/defer date.
	RepeatRule *RepeatRule           `json:"repeat_rule,omitempty"`
	TagIds     *[]openapi_types.UUID `json:"tag_ids,omitempty"`
	Title      string                `json:"title"`
}

// DeferTaskRequest Provide exactly one of input (natural language) or until (explicit timestamp), or clear to remove the defer date.
type DeferTaskRequest struct {
	Clear *bool `json:"clear,omitempty"`

	// Input Natural-language deferral such as "1w", "next monday", "in 3 days" or "mid october"
	Input *string `json:"input,omitempty"`

	// Timezone Overrides the user's stored timezone for this parse
	Timezone *string    `json:"timezone,omitempty"`
	Until    *time.Time `json:"until,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Message Error message
	Message string `json:"message"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	User User `json:"user"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok bool `json:"ok"`
}

// ParseDateRequest defines model for ParseDateRequest.
type ParseDateRequest struct {
	Input string `json:"input"`

	// Kind Picks the default time of day when the phrase has none (defer = start of day, due = 17:00)
	Kind *ParseDateRequestKind `json:"kind,omitempty"`

	// Reference The reference "now" for relative phrases; defaults to the current time
	Reference *time.Time `json:"reference,omitempty"`
	Timezone  *string    `json:"timezone,omitempty"`
}

// ParseDateRequestKind Picks the default time of day when the phrase has none (defer = start of day, due = 17:00)
type ParseDateRequestKind string

// ParseDateResponse defines model for ParseDateResponse.
type ParseDateResponse struct {
	// Interpretation Human-readable explanation of how the phrase was interpreted
	Interpretation string    `json:"interpretation"`
	ResolvedAt     time.Time `json:"resolved_at"`

	// Source Whether the deterministic parser or the AI fallback resolved the phrase
	Source ParseDateResponseSource `json:"source"`
}

// ParseDateResponseSource Whether the deterministic parser or the AI fallback resolved the phrase
type ParseDateResponseSource string

// Project defines model for Project.
type Project struct {
	AvailableTaskCount int        `json:"available_task_count"`
	CompletedAt        *time.Time `json:"completed_at,omitempty"`
	CreatedAt          time.Time  `json:"created_at"`

	// Depth 0 for top-level buckets, 1 for projects inside a bucket, 2 for sub-projects (three levels max)
	Depth          int                `json:"depth"`
	Id             openapi_types.UUID `json:"id"`
	LastReviewedAt *time.Time         `json:"last_reviewed_at,omitempty"`
	Name           string             `json:"name"`
	NextReviewAt   *time.Time         `json:"next_review_at,omitempty"`
	Note           string             `json:"note"`

	// ParentId Parent project; null for top-level projects (buckets)
	ParentId           *openapi_types.UUID `json:"parent_id,omitempty"`
	RemainingTaskCount int                 `json:"remaining_task_count"`
	ReviewIntervalDays int                 `json:"review_interval_days"`

	// Sequential When true, only the first remaining task is available
	Sequential bool          `json:"sequential"`
	SortOrder  int           `json:"sort_order"`
	Status     ProjectStatus `json:"status"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

// ProjectDetail defines model for ProjectDetail.
type ProjectDetail struct {
	Children []Project `json:"children"`
	Project  Project   `json:"project"`
	Tasks    []Task    `json:"tasks"`
}

// ProjectStatus defines model for ProjectStatus.
type ProjectStatus string

// ReorderTasksRequest Full ordering of the project's (or inbox's) active tasks. Tasks not listed keep their relative order after the listed ones.
type ReorderTasksRequest struct {
	TaskIds []openapi_types.UUID `json:"task_ids"`
}

// RepeatRule How a task repeats. "from" controls whether the next occurrence is scheduled relative to the completion date or the previous due/defer date.
type RepeatRule struct {
	Every int            `json:"every"`
	From  RepeatRuleFrom `json:"from"`
	Unit  RepeatUnit     `json:"unit"`
}

// RepeatRuleFrom defines model for RepeatRule.From.
type RepeatRuleFrom string

// RepeatUnit defines model for RepeatUnit.
type RepeatUnit string

// ReviewResponse defines model for ReviewResponse.
type ReviewResponse struct {
	// Due Projects whose next review date has passed, oldest first
	Due []Project `json:"due"`

	// Upcoming Active projects not yet due for review, soonest first
	Upcoming []Project `json:"upcoming"`
}

// Tag defines model for Tag.
type Tag struct {
	// ActiveTaskCount Number of active tasks carrying this tag
	ActiveTaskCount *int `json:"active_task_count,omitempty"`

	// Color Hex color used for the tag chip
	Color     string             `json:"color"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// Task defines model for Task.
type Task struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// DeferUntil Task is hidden from "available" views until this time
	DeferUntil *time.Time `json:"defer_until,omitempty"`
	DroppedAt  *time.Time `json:"dropped_at,omitempty"`
	DueAt      *time.Time `json:"due_at,omitempty"`

	// Flagged Urgent tasks are flagged and rendered prominently
	Flagged bool               `json:"flagged"`
	Id      openapi_types.UUID `json:"id"`

	// IsAvailable Active, not deferred into the future, and its project is active
	IsAvailable bool   `json:"is_available"`
	Note        string `json:"note"`

	// ProjectId Null for inbox tasks
	ProjectId   *openapi_types.UUID `json:"project_id,omitempty"`
	ProjectName *string             `json:"project_name,omitempty"`

	// RepeatRule How a task repeats. "from" controls whether the next occurrence is scheduled relative to the completion date or the previous due/defer date.
	RepeatRule *RepeatRule `json:"repeat_rule,omitempty"`
	SortOrder  int         `json:"sort_order"`
	Status     TaskStatus  `json:"status"`
	Tags       []Tag       `json:"tags"`
	Title      string      `json:"title"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name *string `json:"name,omitempty"`
	Note *string `json:"note,omitempty"`

	// ParentId Null moves the project to the top level
	ParentId           *openapi_types.UUID `json:"parent_id,omitempty"`
	ReviewIntervalDays *int                `json:"review_interval_days,omitempty"`
	Sequential         *bool               `json:"sequential,omitempty"`
	SortOrder          *int                `json:"sort_order,omitempty"`
	Status             *ProjectStatus      `json:"status,omitempty"`
}

// UpdateTagRequest defines model for UpdateTagRequest.
type UpdateTagRequest struct {
	Color *string `json:"color,omitempty"`
	Name  *string `json:"name,omitempty"`
}

// UpdateTaskRequest Partial update. Send null for a nullable field to clear it.
type UpdateTaskRequest struct {
	DeferUntil *time.Time `json:"defer_until,omitempty"`
	DueAt      *time.Time `json:"due_at,omitempty"`
	Flagged    *bool      `json:"flagged,omitempty"`
	Note       *string    `json:"note,omitempty"`

	// ProjectId Null moves the task back to the inbox
	ProjectId *openapi_types.UUID `json:"project_id,omitempty"`

	// RepeatRule How a task repeats. "from" controls whether the next occurrence is scheduled relative to the completion date or the previous due/defer date.
	RepeatRule *RepeatRule           `json:"repeat_rule,omitempty"`
	SortOrder  *int                  `json:"sort_order,omitempty"`
	TagIds     *[]openapi_types.UUID `json:"tag_ids,omitempty"`
	Title      *string               `json:"title,omitempty"`
}

// UpdateUserPreferencesRequest defines model for UpdateUserPreferencesRequest.
type UpdateUserPreferencesRequest struct {
	Timezone *string `json:"timezone,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"created_at"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	LastLoginAt *time.Time          `json:"last_login_at,omitempty"`

	// Name Display name from the Google profile
	Name *string `json:"name,omitempty"`

	// PictureUrl Google profile picture URL
	PictureUrl *string `json:"picture_url,omitempty"`

	// Timezone IANA timezone used to resolve natural-language dates
	Timezone string `json:"timezone"`
}

// UserPreferences defines model for UserPreferences.
type UserPreferences struct {
	Timezone string `json:"timezone"`
}

// GoogleLoginParams defines parameters for GoogleLogin.
type GoogleLoginParams struct {
	// Redirect Frontend path to return to after sign-in
	Redirect *string `form:"redirect,omitempty" json:"redirect,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Status Filter by status; omit for active + on_hold
	Status *ListProjectsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListProjectsParamsStatus defines parameters for ListProjects.
type ListProjectsParamsStatus string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	// View Named view. inbox = no project; available = active and not deferred; flagged = urgent; due = has a due date (soonest first); completed = recently completed; all = every active task
	View *ListTasksParamsView `form:"view,omitempty" json:"view,omitempty"`

	// ProjectId Only tasks in this project
	ProjectId *openapi_types.UUID `form:"project_id,omitempty" json:"project_id,omitempty"`

	// TagId Only tasks carrying this tag
	TagId *openapi_types.UUID `form:"tag_id,omitempty" json:"tag_id,omitempty"`

	// Q Case-insensitive title/note search
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListTasksParamsView defines parameters for ListTasks.
type ListTasksParamsView string

// CreateApiTokenJSONRequestBody defines body for CreateApiToken for application/json ContentType.
type CreateApiTokenJSONRequestBody = CreateApiTokenRequest

// ParseDateJSONRequestBody defines body for ParseDate for application/json ContentType.
type ParseDateJSONRequestBody = ParseDateRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagRequest

// UpdateTagJSONRequestBody defines body for UpdateTag for application/json ContentType.
type UpdateTagJSONRequestBody = UpdateTagRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTaskRequest

// ReorderTasksJSONRequestBody defines body for ReorderTasks for application/json ContentType.
type ReorderTasksJSONRequestBody = ReorderTasksRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// DeferTaskJSONRequestBody defines body for DeferTask for application/json ContentType.
type DeferTaskJSONRequestBody = DeferTaskRequest

// UpdateUserPreferencesJSONRequestBody defines body for UpdateUserPreferences for application/json ContentType.
type UpdateUserPreferencesJSONRequestBody = UpdateUserPreferencesRequest
